version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 8001:3306
    environment:
      MYSQL_DATABASE: blueviolet
      MYSQL_USER: alliwannadev
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci